name: Fetch and Commit Daily Holidays

on:
  schedule:
    - cron: '1 21 * * *'
  workflow_dispatch:

jobs:
  fetch_holidays:
    runs-on: windows-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install selectolax patchright playwright
      
      - name: Install Google Chrome
        run: choco install googlechrome --no-progress -y

      - name: Run parser.py to fetch holidays
        run: python parser.py

      - name: Check for changes and commit holidays.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'holidays.json'
          commit_message: 'Holidays updated!'
          commit_author: Im Mock <just@mock.com>
