name: Fetch and Commit Daily Holidays

on:
  schedule:
    - cron: '1 21 * * *'
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Retry attempt number'
        required: false
        default: '0'

jobs:
  fetch_holidays:
    runs-on: windows-latest
    
    permissions:
      contents: write
      actions: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install selectolax patchright playwright
      
      - name: Install Google Chrome
        run: choco install googlechrome --no-progress -y --ignore-checksums

      - name: Run parser.py to fetch holidays
        run: python parser.py

      - name: Validate holidays.json and retry if needed
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RETRY_COUNT: ${{ github.event.inputs.retry_count || '0' }}
        run: |
          $retryCount = [int]$env:RETRY_COUNT
          $maxRetries = 5
          $isValid = $false
          
          if (Test-Path "holidays.json") {
            $content = Get-Content "holidays.json" -Raw -ErrorAction SilentlyContinue
            
            if ($content) {
              $json = $content | ConvertFrom-Json -ErrorAction SilentlyContinue
              if ($json -and $json.holidays -and $json.holidays.Count -gt 0) {
                $isValid = $true
              }
            }
          }
          
          if (-not $isValid) {
            if ($retryCount -lt $maxRetries) {
              $newRetryCount = $retryCount + 1
              Start-Sleep -Seconds 60
              gh workflow run fetcher.yml --ref $env:GITHUB_REF_NAME --field retry_count=$newRetryCount
              exit 1
            } else {
              exit 1
            }
          }

      - name: Check for changes and commit holidays.json
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'holidays.json'
          commit_message: 'Holidays updated!'
          commit_author: Im Mock <just@mock.com>
